---
title: Jesal Mehta
timezone: Asia/Kolkata
collections:
  explorations:
    title: Explorations
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  work:
    title: Work
    output: true
  curiosities:
    title: Cabinet Of Curiosities
    output: true
defaults:
- scope:
    path: ''
    type: explorations
  values:
    layout: exploration
- scope:
    path: ''
    type: work
  values:
    layout: project
- scope:
    path: ''
    type: curiosities
  values:
    layout: curiosity
    permalink: /cabinet-of-curiosities/:title
permalink: pretty
exclude:
- Gruntfile.js
- Gemfile
- Gemfile.lock
- package.json
- README*
- node_modules
- ".gitignore"
plugins:
- jekyll-seo-tag
- jekyll-sitemap
sass:
  sass_dir: styles/
  style: compressed
logo: '/uploads/logo.png'
logo_white: '/uploads/logo-white.png'
