---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: _curiosities
  label: Curiosities
  create: all
  match: "**/*"
  templates:
  - curiosity-829d784f-9267-41b5-8255-afb497d9b7b7
- type: jekyll-pages
  label: Pages
  create: all
- type: directory
  path: _work
  label: Work
  create: all
  match: "**/*"
- type: directory
  path: _uploads
  label: Uploads
  create: all
  match: "**/*"
- type: directory
  path: _services
  label: Services
  create: all
  match: "**/*"
- type: jekyll-posts
  label: Posts
  create: all
- type: directory
  path: _explorations
  label: Explorations
  create: all
  match: "**/*"
  templates:
  - post
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
